### ISSUE TITLE
Virtual points to BEV map

### ISSUE THREAD

**Issue by sangjinpark97** [hailanyi/VirConv#11]
Hi, thank you for nice work!

I tried to convert virtual points to BEV maps.

I generated the virtual points from the point clouds of KITTI using your code.

But, when I convert to the generated virtual points to BEV maps. The output is weird as below.

The blue points in the image indicate the virtual points and remaining points are original point  clouds.

Have you tried to make BEV map with virtual points or Can you assume the reason?

Thank you in advance!

![image](https://user-images.githubusercontent.com/60248657/229387402-e908432c-6b80-4c0d-b3ba-a8b547f17f40.png)

* Updated

I visualize the virtual points in 3D. The results is as follows.

![image](https://user-images.githubusercontent.com/60248657/229392070-2bb0f476-62ae-4bc0-9122-4d28f79ee738.png)

**Comment by hailanyi** [comment]
Can you provide your code? I'm not sure what happened. From the distribution, seems that your points are in  the spherical coordinate system instead of the Cartesian coordinate system.

**Comment by sangjinpark97** [comment]
Hi, thank you for your response!

The output was very unstable because the weight path was wrong.

I successfully generate the depth map!

But, I do not perform 'la_sampling2' function in my project because my model doesn't use the voxelization. 

For this reason. I assume the BEV results is very noisy.

The output and BEV from the virtual points are as follows.

Network Output:
![image](https://user-images.githubusercontent.com/60248657/229721485-94d1ebb2-8c50-42c5-9115-e70de700f384.png)

BEV from virtual points
![image](https://user-images.githubusercontent.com/60248657/229722330-85a3aa3d-8c4c-4b4e-9bf2-66f6f7ef2421.png)

Can you tell me if my opinion is reasonable? If so, can I try la_sampling without voxel information?

Thank you!

**Comment by hailanyi** [comment]
Ok, I see. The la_samling2 and la_samling in our code perform the same function of points down-sampling ( just for save storage space). Note that, the voxel sampling is performed in the spherical coordinate system (range image plane), not the BEV plane.

The la_samling2 is a c++ version while the la_samling is a python version. So the la_sampling2 is much faster than la_sampling. If you want to keep all points, two function cannot be used.

**Comment by sangjinpark97** [comment]
Thank you for your help !

**Comment by Goooyi** [comment]
> Hi, thank you for your response!
> 
> The output was very unstable because the weight path was wrong.
> 
> I successfully generate the depth map!
> 
> But, I do not perform 'la_sampling2' function in my project because my model doesn't use the voxelization.
> 
> For this reason. I assume the BEV results is very noisy.
> 
> The output and BEV from the virtual points are as follows.
> 
> Network Output: ![image](https://user-images.githubusercontent.com/60248657/229721485-94d1ebb2-8c50-42c5-9115-e70de700f384.png)
> 
> BEV from virtual points ![image](https://user-images.githubusercontent.com/60248657/229722330-85a3aa3d-8c4c-4b4e-9bf2-66f6f7ef2421.png)
> 
> Can you tell me if my opinion is reasonable? If so, can I try la_sampling without voxel information?
> 
> Thank you!

Hi, I also want to generate the depth info from it, can you explain how you get the the depth map? thanks

**Comment by sangjinpark97** [comment]
> > Hi, thank you for your response!
> > The output was very unstable because the weight path was wrong.
> > I successfully generate the depth map!
> > But, I do not perform 'la_sampling2' function in my project because my model doesn't use the voxelization.
> > For this reason. I assume the BEV results is very noisy.
> > The output and BEV from the virtual points are as follows.
> > Network Output: ![image](https://user-images.githubusercontent.com/60248657/229721485-94d1ebb2-8c50-42c5-9115-e70de700f384.png)
> > BEV from virtual points ![image](https://user-images.githubusercontent.com/60248657/229722330-85a3aa3d-8c4c-4b4e-9bf2-66f6f7ef2421.png)
> > Can you tell me if my opinion is reasonable? If so, can I try la_sampling without voxel information?
> > Thank you!
> 
> Hi, I also want to generate the depth info from it, can you explain how you get the the depth map? thanks

Sorry for late answer.

I just generate the depth map using PENet whose information is in this repository.

**Comment by wjwless** [comment]
Hi, my visualization result boxes are all messed up, but the evaluation results are fine, I don't know if there is any problem parsing the pkl file, if you still have the code, can you share it? 可以的话请发送邮箱至wjw0101@foxmail.
com thanks a lot!
