### ISSUE TITLE
ValueError: cannot reshape array of size 532416 into shape (104199,8)

### ISSUE THREAD

**Issue by buaa18231157-YLH** [hailanyi/VirConv#15]
It seems that at certain iterations of training process it will raise ValueError. Please help me

**Comment by hailanyi** [comment]
This may be a data handling issue, please completely delete the previous OpenPCDet version and use the code provided by this repository to generate the dataset infos.

**Comment by hailanyi** [comment]
1 I usually did not use the demo.py to show the results, instead, I use myself [visualization code](https://github.com/hailanyi/3D-Detection-Tracking-Viewer) to view the results. You can copy the code from ours or SFD to view results.
2 We have explained in our paper, please carefully read again. The VirConv-L, VirConv-T did not use odometry data, only VirConv-S used the odometry data. 
3 We have explained in our paper, please carefully read again. The VirConv-L is based on early fusion，the VirConv-T and VirConv-S is based on late fusion.

**Comment by buaa18231157-YLH** [comment]
----- 原始邮件 -----
发件人：Hailanyi ***@***.***>
收件人：hailanyi/VirConv ***@***.***>
抄送人：Lehang Yu ***@***.***>,  Author ***@***.***>
主题：Re: [hailanyi/VirConv] ValueError: cannot reshape array of size 532416 into shape (104199,8) (Issue #15)
日期：2023年04月22日 22点09分


1 I usually did not use the demo.py to show the results, instead, I use myself visualization code to view the results. You can copy the code from ours or SFD to view results.

2 We have explained in our paper, please carefully read again. The VirConv-L, VirConv-T did not use odometry data, only VirConv-S used the odometry data.

3 We have explained in our paper, please carefully read again. The VirConv-L is based on early fusion，the VirConv-T and VirConv-S is based on late fusion.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread. three different
Thanks for your reply.Q2&Q3 of my last replication were quite worthless as I didn't notice chapter3.4, which in detail proposes the framework of 3 different VirConvs. I'm a novice at reading literature so I'm really sorry for raising such silly questions.Here's another point I feel hard to understand. Below is an original text from VirConv paper:
"we observed that a huge number of virtual points introduced for nearby objects are redundant. Specifically, 97% of virtual points from the nearby objects bring only a 0.18% performance improvement, while 3% of virtual points for the faraway objects bring a 2.2% performance improvement."
Does this mean that 97% of the points in the entire virtual pointcloud come from closer objects, while points on farther objects only account for 3%? Your article also mentioned that the virtual point cloud generated by deep completion is very dense, and generally view from the image, the number of pixels occupied by closer objects is  a relative small number, which is definitely not comparable to a large number of background points. How can it account for 97% of the proportion and can be called as "huge number"?
This is just a small confusion. Personally I'm quite agree with your theory of large number of redundant while noisy points from virtual pointclouds.

Looking forward to your early reply.Best wishes,__

**Comment by hailanyi** [comment]
Figure 2e is the statistics of the internal points of object ( did not include background). Please see the legend: 'LiDAR points per object' and 'Virtual points per object'. Besides, the 97% and 3% is based on a large distance threshold of 35m. So I think the conclusion is  convincing.

**Comment by buaa18231157-YLH** [comment]
Thanks for your immediate response. 
Generally I found an issue while reading NRConv part. Below is an original text from your paper:
"Specifically, given N input voxels formulated by a 3D indices vector H ∈ R(N × 3) and a features vector X ∈ R(N × Cin)......"
The question is, how can we get a feature vector X firstly so that the first NRConv layer can use it as input?
In figure 3.4(c), The fused, stochastically discarded pointcloud voxels is directly handled by VirConvnet. However, StVD layer is just followed by NRConv. without a certain backbone, we cannot get feature vector X priorly, which hampers the computation of geometry feature Y ∈ R(N × Cout). 
Looking forward to your early reply.
Best wishes,
__
----- 原始邮件 -----
发件人：Hailanyi ***@***.***>
收件人：hailanyi/VirConv ***@***.***>
抄送人：Lehang Yu ***@***.***>,  Author ***@***.***>
主题：Re: [hailanyi/VirConv] ValueError: cannot reshape array of size 532416 into shape (104199,8) (Issue #15)
日期：2023年04月25日 11点21分


Figure 2e is the statistics of the internal points of object ( did not include background). Please see the legend: 'LiDAR points per object' and 'Virtual points per object'. Besides, the 97% and 3% is based on a large distance threshold of 35m. So I think the conclusion is  convincing.

&mdash;
