### ISSUE TITLE
KITTI Visual Odometry dataset download

### ISSUE THREAD

**Issue by vehxianfish** [hailanyi/VirConv#16]
Hi, Thanks for your excellent work.
if I want to generate a semi-dataset. which dataset needs to download as follows.
thanks a lot. @hailanyi 
![image](https://user-images.githubusercontent.com/40848953/233531066-b12db160-4767-4b0b-9e6e-4ffeb0029349.png)

**Comment by vehxianfish** [comment]
Another question occurs. The PENET weights downloaded can not be untared. Can you hang up a Baidu connection or send it to me by email？
Email:s_xu@foxmail.com
Thanks a lot.

**Comment by vehxianfish** [comment]
Otherwise, the velodyne_depth folder contains the fusion result of raw lidar and RGB virtual points?
Thanks a lot.
@hailanyi

**Comment by hailanyi** [comment]
1 Please download the  color image, velodyne laser data and calibration file, and organise the files as in readme.
2 You can download the weights from this baidu [link(gp68)](https://pan.baidu.com/s/1tBVuqvBZ0ns79ARmNpgwWw).
3 Yes.

**Comment by vehxianfish** [comment]
> 

thanks a lot
