### ISSUE TITLE
Read depth from velodyne_depth

### ISSUE THREAD

**Issue by Goooyi** [hailanyi/VirConv#17]
Thanks for your works,

I downloaded the `velodyne_depth` set, but not sure how to extract the depth info from it, can you give me some guide?

**Comment by hailanyi** [comment]
I recommend using PENet (in the VirConv/tools/PENet) to generate the depth map. The depth in ```velodyne_depth``` has been transformed into virtual points. So it requires calibration parameters to project back to the image plane.
