### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by Omar-Aldade** [hailanyi/VirConv#18]
the detected cuda version (11.1) mismatches the version that was used to compile pytorch (10.2). I got this error and could solve it by installing cuda 10.2 version. Can u please check, if the cuda version mentioned in the requirements is the right one?

**Comment by hailanyi** [comment]
I used the pytorch 1.8.1, please refer to the Dependency in readme. But someone used pytorch 1.8.2, it also works see [issue 12](https://github.com/hailanyi/VirConv/issues/12).
