### ISSUE TITLE
Didnt see Input StVD, where is the code? thx

### ISSUE THREAD

**Issue by Raiden-cn** [hailanyi/VirConv#19]
Layer StVD as training data augmentation  shown in https://github.com/hailanyi/VirConv/blob/2079960e06d2135b10a623c09fc084df568fa2fa/pcdet/models/backbones_3d/spconv_backbone.py#L609 about VirConv-L.
where is Input StVD?

**Comment by hailanyi** [comment]
The input voxel discard has been changed to [input point discard](https://github.com/hailanyi/VirConv/blob/master/pcdet/datasets/dataset.py) for faster voxelization.
