### ISSUE TITLE
How to reproduce the results on the KITTI test set?

### ISSUE THREAD

**Issue by Devoe-97** [hailanyi/VirConv#2]
This is an excellent work, but how to reproduce the results on the KITTI test set？

**Comment by Devoe-97** [comment]
And could you share the config for 3 classes?

**Comment by hailanyi** [comment]
1. Please refer the official [OpenPCDet](https://github.com/open-mmlab/OpenPCDet) for more details of test set submission.
2. The 3-cls config is similar with [CasA-V](https://github.com/hailanyi/CasA). But the performance is not very stable. Please consider adjusting the backbone's parameters and the training epochs if you can't achieve the desired performance.
