### ISSUE TITLE
pretrained PENet file dosn't exist

### ISSUE THREAD

**Issue by Omar-Aldade** [hailanyi/VirConv#22]
Hello again,

This issue is not directly related to your work. I'm trying to download the pretrained PENet model for which you mentioned the link in this repo, but the files doesn't exist anymore. I need the model weights of the PENet for an experiment on VirConv-L. So if you have the file somewhere else, can you please upload it and send me the link?

Thank you so much in advance

**Comment by hailanyi** [comment]
Here is a [baidu pan link (gp68)](https://pan.baidu.com/s/1tBVuqvBZ0ns79ARmNpgwWw). I also updated in readme.

**Comment by Omar-Aldade** [comment]
Thank you for your fast reply. I believe i need some kind of extraction code to be able to download the file from baidu.com

**Comment by hailanyi** [comment]
The code is the gp68.
