### ISSUE TITLE
Will the metrics on nuScenes be made public in the future?

### ISSUE THREAD

**Issue by hopef** [hailanyi/VirConv#26]
Thanks for your effort, I would like to compare your work with the popular detectors on nuScenes, but I couldn't find any data.

**Comment by hailanyi** [comment]
The detailed metrics are [here](https://openaccess.thecvf.com/content/CVPR2023/supplemental/Wu_Virtual_Sparse_Convolution_CVPR_2023_supplemental.pdf)
