### ISSUE TITLE
Code for validation on the nuscenes dataset

### ISSUE THREAD

**Issue by crinoiddream** [hailanyi/VirConv#3]
Thank you very much for your work. I was wondering if you have plans to release the code for validation on the nuscenes dataset?

**Comment by hailanyi** [comment]
Our submission on nuScenes is based on the [mmdetection3d](https://github.com/open-mmlab/mmdetection3d), which is not very compatible with this OpenPCDet. Our performance on nuScenes is also not very good, so we will not release the code.

**Comment by crinoiddream** [comment]
Received, thanks for your response

**Comment by ChunZheng2022** [comment]
@crinoiddream Hi, I have considered the same question as you, and after carefully reading the original paper, I have found that the entire network is named VirConvNet, and the new operation name is VirConv, so the convolution operation of VirConv was likely used here.

**Comment by BaotWang** [comment]
Is there any plan to open source the code for virtualization processing of nuscenes data sets?
