### ISSUE TITLE
About the inference speed

### ISSUE THREAD

**Issue by Orbis36** [hailanyi/VirConv#30]
Thanks for your excellent work first.
My only question is when you test your inference speed, you mentioned that your method only needs around 60ms for a single frame, however, from the PENet paper, they need 40ms to get the completed depth map.
Without considering any transfer time between the depth map and pseudo points, do you only need 20ms for forward propagation? Considering a typical Voxel-RCNN needs 40ms to infer a frame, I'm confused why you can do it so fast.

Thanks for any help.

**Comment by hailanyi** [comment]
Indeed, our method is tested on 3090 GPU (~0.2ms) while the PENet is tested on 2080 (0.032ms in paper). We also used the code mentioned in PENet paper to  test the speed. However, I noticed recently that the speed measure has some problems, please refer to the readme of PENet code. If you want to go faster, you might use a more efficient completion network. The detection accuracy is similar.

**Comment by Orbis36** [comment]
OK, thx for the reply.
You mean 0.2s right? 0.2ms means 5000FPS, which sounds too fast.

**Comment by hailanyi** [comment]
My mistake, should be 0.02s vs 0.032s
