### ISSUE TITLE
RCNN_RECALL非常高，但是ROI_RECALL接近于零

### ISSUE THREAD

**Issue by Gmonster-24** [hailanyi/VirConv#31]
RCNN_RECALL非常高，但是ROI_RECALL接近于零，对最终在test数据集上验证模型有效性有影响吗？另外，我们没有对dense head进行改动。

**Comment by hailanyi** [comment]
没事的，对精度没影响，这个RoI recall接近0是因为gt和roi没在同一个变换下，统一到同一个变换下就很高了

**Comment by WuYanXingege** [comment]
> 没事的，对精度没影响，这个RoI recall接近0是因为gt和roi没在同一个变换下，统一到同一个变换下就很高了

您好，我想问问变换在代码中如何修改可以使gt和roi对齐，从而正确产生RoI recall
