### ISSUE TITLE
ERROR in testset results

### ISSUE THREAD

**Issue by gw0522** [hailanyi/VirConv#32]
Hello, may I ask why my evaluation in the val set is normal, but when the evaluation results in the test set are submitted to the official evaluation but it shows zero. Where is the problem and how should we modify it? Thank you for your time
![574a40cd54ccc58796e0798341aecce](https://github.com/hailanyi/VirConv/assets/108254524/2ee1e5ec-ebc4-40f0-b4e2-df9e7f8e4950)

**Comment by hailanyi** [comment]
Please check your config and use the test set split and infos for testing. Besides, the detection confidence should be included in your detection results.
