### ISSUE TITLE
Questions about the "def roi_grid_pool_mm" in the VirConv-L?

### ISSUE THREAD

**Issue by weilli** [hailanyi/VirConv#40]
Thanks for your excellent job! I have some questions about the code.
I thought the VirConv-L is the early fusion. Why does the function "roi_grid_pool_mm exist" in the TEDMHead?

**Comment by hailanyi** [comment]
Just for code simplicity. The feature will be replaced by lidar feature if no mm feature provided. Please refer to line 608 to 611 in ted_head.py .
