### ISSUE TITLE
Script for Test Set

### ISSUE THREAD

**Issue by IbrahimUWA** [hailanyi/VirConv#45]
Hello,
I am a PhD student at the University of Western Australia. Currently, I am working on 3D Object Detection using KITTI dataset. I came across your amazing work for object detection. Could you share the script to generate the test results? I will be grateful to you. 

Best regards
Ibrahim

**Comment by hailanyi** [comment]
Hi Ibrahim!
    Thanks for your attention to our work. Please change the [config](https://github.com/hailanyi/VirConv/blob/master/tools/cfgs/dataset_configs/kitti_dataset.yaml) as follows:
```
DATA_SPLIT: {
    'train': train,
    'test': test
}

INFO_PATH: {
    'train': [kitti_infos_train.pkl],
    'test': [kitti_infos_test.pkl],
}
```
During testing, please set the --save_to_file in [test.py](https://github.com/hailanyi/VirConv/blob/master/tools/test.py) to True:
```
parser.add_argument('--save_to_file', action='store_true', default=True, help='')
```
The results are automatically saved to 'output/models/kitti/......'.

**Comment by IbrahimUWA** [comment]
Hello Hailanyi,

Thank you so much for your kind reply. You have done impressive work. I really appreciate it.

Thank you.

Kind regards,
Muhammad Ibrahim

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
