### ISSUE TITLE
Questions about the leaderboard's inference time

### ISSUE THREAD

**Issue by jisoo0-0** [hailanyi/VirConv#58]
Hi, thank you for your wonderful work.

I wonder if this version of the code is the one you reported on the official site of the KITTI competition in terms of the environment(1 core @ 2.5 Ghz (C/C++)). 

Thanx.

**Comment by hailanyi** [comment]
No, it is based on 3090 GPU and pytorch framework.

**Comment by Chrislai502** [comment]
Hey, a quick follow up question on this, does inference only need 1 single GPU? 
Thanks in advance!
