### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by 1zsw123** [hailanyi/VirConv#6]
I don‘t see the test file has --format-only --eval-options. So how to get the kitti style file and submission? Can you tell me how you submit the result to kitti ? Is the default result.pkl is ok? Thank you so much.

**Comment by hailanyi** [comment]
Please refer to the official OpenPCDet. Set the ‘--save_to_file’ to True, the results will be saved in a KITTI format.

**Comment by 1zsw123** [comment]
Yes, I use it. But the result is ERROR: Couldn't read: 000000.txt 
An error occurred while processing your results.
Please make sure that the data in your zip archive has the right format!
And I find out that the final_result is 7480, not 7517.Why?

**Comment by 1zsw123** [comment]
I mean 'ERROR: Couldn't read: 000000.txt
An error occurred while processing your results.
Please make sure that the data in your zip archive has the right format! 'is kitti submission report.

**Comment by hailanyi** [comment]
Please set the data split of the config to ‘test’ to produce your submission results.

**Comment by 1800710138** [comment]
> I mean 'ERROR: Couldn't read: 000000.txt An error occurred while processing your results. Please make sure that the data in your zip archive has the right format! 'is kitti submission report.

Have you solved it yet? I also encountered this situation, how did I solve it
