### ISSUE TITLE
Modified version of generating Semi dataset

### ISSUE THREAD

**Issue by jisoo0-0** [hailanyi/VirConv#61]
Hi, i am leaving an issue for those who are struggling to generate a semi dataset.

Using the code available in this Git repository results in a semi dataset that is sampled without being sorted, which makes it impossible to construct the same dataset as the author.

Therefore, I have modified the code and deployed it using the link below.

https://github.com/jisoo0-0/VirConv

**Comment by zllxot** [comment]
hi, when i try to generate semi dataset from odometry, I get an error as follow:

```
> python3 creat_semi_dataset.py ../data/odometry ../data/kitti/semi
0 / 10888
Traceback (most recent call last):
  File "/data1/zllxot/VirConv/tools/creat_semi_dataset.py", line 74, in <module>
    move_data(input_path_dict, out_path)
  File "/data1/zllxot/VirConv/tools/creat_semi_dataset.py", line 67, in move_data
    copy_calib(in_calib_path, out_calib_path)
  File "/data1/zllxot/VirConv/tools/creat_semi_dataset.py", line 30, in copy_calib
    Tr = 'Tr_velo_to_cam'+all_info[4][2:]
IndexError: list index out of range
```

Have you encountered this too?

**Comment by wittycheng** [comment]
> ?

I have also met this problem, do you have any solution?
