### ISSUE TITLE
How to detect object accuracy at different distances

### ISSUE THREAD

**Issue by xueking1** [hailanyi/VirConv#62]
Hello, author! 
May I ask how to detect the detection accuracy and accuracy improvement at different distances as shown in Figure 7?
Thank U!

**Comment by xueking1** [comment]
I've solved the problem myself

**Comment by Karkers** [comment]
I want to know how to solve this problem!!!!!!!Thanks

**Comment by xueking1** [comment]
> I want to know how to solve this problem!!!!!!!Thanks

You can see the link to the relevant file from my home page.
