### ISSUE TITLE
visually view

### ISSUE THREAD

**Issue by mihudaner** [hailanyi/VirConv#7]
你好按照说明下载数据集和配置了环境，并且可以运行test.py我想请教一下如何可视化的看检测的输入点云和检测结果box

Hello, follow the instructions to download the dataset, configure the environment, and run test.py. I would like to ask how to visually view the input point cloud and result box @hailanyi

**Comment by hailanyi** [comment]
你可以参考[OpenPCDet](https://github.com/open-mmlab/OpenPCDet)的可视化方法。
或者你可以使用我之前的可视化代码库[detection viewer](https://github.com/hailanyi/3D-Detection-Tracking-Viewer)进行可视化。
