### ISSUE TITLE
THC/THC.h doesn't exist

### ISSUE THREAD

**Issue by AinaraC** [hailanyi/VirConv#77]
Hi!

I'm trying to run a model on a Jetson Orin with CUDA 12.6 and PyTorch 2.5.0, but it seems like the THC library doesn't exist anymore. I really need to run the model with these versions because my Jetson doesn't support earlier versions. 

If anyone is facing this problem, I would be very grateful for your help.

**Comment by AinaraC** [comment]
In later versions of PyTorch, the THC library has been replaced by ATen.

I've found the solution on the [OpenPCDet](https://github.com/open-mmlab/OpenPCDet) official repository. Some of the pcdet/ops scripts have been updated in this repository, so you can download them directly from there. 

According to this [issue](https://github.com/open-mmlab/OpenPCDet/pull/1041), for the remaining scripts, you can remove the following lines:
```
#include THC/THC.h
extern THCState *state;
```
It works fine for me.

**Comment by Puiching-Memory** [comment]
After torch1.11, THC was removed
