### ISSUE TITLE
Multi-class training

### ISSUE THREAD

**Issue by minju-Kang** [hailanyi/VirConv#8]
Hi, thank you for sharing your code.
In the configuration file, there are only 'Car' class. I want to train your model with 'pedestrian' and 'cyclist'. Could you share the configuration file for multi-class training?

**Comment by hailanyi** [comment]
The 3-cls config is similar with [CasA-V](https://github.com/hailanyi/CasA). But the performance is not stable. Please consider adjusting the backbone's parameters and the training epochs if you can't achieve a desired performance.
